# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dapper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dapper

  target 'DapperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DapperUITests' do
    inherit! :search_paths
    # Pods for testing
  end

platform :ios, '10.3'
target :'Dapper' do
    use_frameworks!
    pod 'AWSMobileClient', '~> 2.6.13'
    # other pods
end

end
